project:
  type: website
  resources:
  - "pdf/*.pdf"
  
website:
  title: "    "
format:
  html:
    theme: ember.scss
    css: custom.scss
    #self-contained: true
    grid:
        sidebar-width: 400px
        body-width: 600px
        #margin-width: 300px
        #gutter-width: 1em
    linestretch: 1.3
    fontsize: 1.3em
    smooth-scroll: true
    linkcolor: "#62259d"
    link-external-newwindow: true
  docx: 
    reference-doc: vma-letterhead.docx
  PrettyPDF-pdf: default

