(function(r,q,w,t,l){r[q]=r[q]||{};for(r[q].q=r[q].q||[];l<t.length;)w(t[l++],r[q])})(window,"extole",function(r,q){q[r]=q[r]||function(){q.q.push([r,arguments])}},["log"],0);
extole.define||function(){function r(d){d=l(d);return f[d]}function q(d,k){extole.log("error","[REQUIRE] "+d,k)}function w(d,k){if(d.length)for(var m=0;m<d.length;m++)k(d[m],m);else for(m in d)Object.prototype.hasOwnProperty.call(d,m)&&k(d[m],m)}function t(d,k){var m=[];w(d,function(u,x){m[x]=k(u,x)});return m}function l(d){return"string"!==typeof d?d:/origin-\d/.test(d)?d.substring(d.indexOf("type=")).replace(/version=\d+:/,""):d}function v(d){var k=d.split("/").slice(-1)[0],m=k.length;w(k.toLowerCase(),
function(u){m+=" abcdefghijklmnopqrstuvwxyz1234567890-_.".indexOf(u)});return d.replace("origin","origin-"+m%8)}function h(d){var k=/^extole-creatives:/.test(d),m=/^extole-media:/.test(d),u=/^core-root:\/\//.test(d),x=/^extole-assets:/.test(d),C=/origin\./.test(d),z=/^http:/.test(d),D=/^https:/.test(d);return k?(d=d.slice(17),h("extole-assets:/core-modules/"+d)):x?(d=d.slice(14),h("extole-media:/assets/"+d)):m?(d=d.slice(13),d=extole.CORE_ROOT+d,h(d)):u?(d=d.slice(12),d=extole.CORE_ROOT+d,h(d)):C?
(d=v(d),d+="?site="+window.location.hostname,h(d)):z?(d=d.slice(5),h(d)):D?(d=d.slice(6),h(d)):d}function g(){}function e(){var d="undefined"!==typeof window.opera&&"[object Opera]"===window.opera.toString(),k=document.createElement("script");this.useInteractive=k.attachEvent&&!(k.attachEvent.toString&&0>k.attachEvent.toString().indexOf("[native code"))&&!d}function c(){w(f,function(d){d._fetched?d._defined||d.define():d.fetch()})}function a(d,k,m,u,x){if("$config"!=d){var C=r(d),z=C||new g;C||(C=
l(d),f[C]=z);d&&k&&(z._fetched=!0);z.start=z.start||(new Date).getTime();z.url=z.url||d;z.dependencies=z.dependencies||k;z.config=z.config||u;z.definedCallback=z.definedCallback||m;z.isRequire=z.isRequire||x}}function b(d,k,m,u){d instanceof Array&&(u=m,m=k,k=d,d=void 0);n.addDefine({url:d,dependencies:k,definedCallback:m,config:u})}var f={};g.prototype={getUnresolvedDependencies:function(){var d=[];w(this.dependencies,function(k){"$config"!=k&&(k=r(k),(!k||k&&!k._defined)&&d.push(k))});return d},
getDependencies:function(){var d=this,k=[];w(d.dependencies,function(m){m="$config"==m?d.config||null:r(m).definition||null;k.push(m)});return k},define:function(){function d(x){k.definedCallback=void 0;k.definition=x;k.end=(new Date).getTime();k.timeToDefine=k.end-k.start;k._defining=!1;k._defined=!0;setTimeout(c,1)}var k=this;k.defineStartTime=k.defineStartTime||(new Date).getTime();if(!k._defining&&!k._defined&&k.dependencies)if(k._defining=!0,0<k.getUnresolvedDependencies().length)k._defining=
!1;else{var m=k.getDependencies(),u={isAsync:!1,async:function(){k.isAsync=!0;u.isAsync=k.isAsync;return function(x){d(x)}}};(function(){if(k.definedCallback){var x=k.definedCallback;x=x&&x.apply(u,m);u.isAsync||d(x)}else d(!0)})()}},fetch:function(){var d=this;d._fetching||d._fetched||(d.url?(d._fetching=!0,d.startFetchTime=(new Date).getTime(),n.loadModule(d.url,function(){d._fetching=!1;d.endFetchTime=(new Date).getTime();d.timeToFetch=d.endFetchTime-d.startFetchTime;d._fetched=!0;d.define()})):
q("Tried to fetch a module without a url - dependencies: "+d.dependencies+" definedCallback: "+(d.definedCallback?"exists":"null")+" config: "+d.config))}};e.prototype={defineQueue:[],interactiveScript:null,currentlyAddingScript:null,getInteractiveScript:function(){if(n.interactiveScript&&"interactive"==n.interactiveScript.readyState)return n.interactiveScript;for(var d=document.getElementsByTagName("head")[0].getElementsByTagName("script"),k,m=d.length-1;0<=m;m--){var u=this.getScriptDataUrl(d[m]);
d[m]&&"interactive"==d[m].readyState&&u&&(k=d[m])}return k},scriptUrlAttributeName:"data-extole-require-url",getScriptDataUrl:function(d){return d.getAttribute(this.scriptUrlAttributeName)},setScriptDataUrl:function(d,k){d.setAttribute(this.scriptUrlAttributeName,k)},attachOnLoad:function(d,k){function m(C){var z=d.readyState;if(u&&"interactive"==z)this.interactiveScript=d;else if("load"===C.type||x.test(z))u?d.detachEvent("onreadystatechange",m):d.removeEventListener("load",m,!1),k(C)}k=k||function(){};
var u=this.useInteractive,x="PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/;u?d.attachEvent("onreadystatechange",m):d.addEventListener("load",m,!1)},defineTimeout:null,addDefine:function(d){if(d.url)d.url=h(d.url);else{var k=this.currentlyAddingScript||this.getInteractiveScript();this.useInteractive&&k&&(k=this.getScriptDataUrl(k),d.url=k,this.interactiveScript=null)}d.dependencies=t(d.dependencies,h);this.useInteractive&&!d.url&&q("defines should not be missing a url in ie.");
this.defineQueue.push(d);this.defineTimeout&&clearTimeout(this.defineTimeout);var m=this;this.defineTimeout=setTimeout(function(){m.intakeDefines()},1)},intakeTimeout:null,intakeDefines:function(){for(var d=[],k;k=this.defineQueue.shift();){var m=[];w(k.dependencies,function(u){u&&m.push(u)});k.url&&r(k.url);k.url||d.push("deps "+k.dependencies);w(m,function(u){a(u)});a(k.url,m,k.definedCallback,k.config,k.isRequire)}this.intakeTimeout&&clearTimeout(this.intakeTimeout);this.intakeTimeout=setTimeout(c,
1)},loadModule:function(d,k){var m=document.createElement("script");m.async=!0;m.crossOrigin="anonymous";this.setScriptDataUrl(m,d);var u=this;this.attachOnLoad(m,function(){clearTimeout(x);if(!u.useInteractive){for(var z,D=u.defineQueue.length-1;0<=D;D--)u.defineQueue[D].url||(z&&q("Multiple anonymous modules loaded in one script - "+d),z=u.defineQueue[D]);z&&(z.url=d)}u.intakeDefines();k&&k(null)});m.src=d;var x=setTimeout(function(){extole.log("warn","[REQUIRE] Module did not load within 2000ms: ",
{moduleUrl:d})},2E3);this.currentlyAddingScript=m;var C=document.getElementsByTagName("head")[0]||document.head;C?C.appendChild(m):extole.log("warn","[REQUIRE] <head> element not found on trying to load "+d,void 0);this.currentlyAddingScript=void 0}};var n=new e;b.getModule=function(d){return r(d)};var p=0;extole.define=b;extole.require=function(d,k){var m=n,u=m.addDefine;p++;u.call(m,{url:"anonymous_"+p,dependencies:d,definedCallback:k,isRequire:!0})};extole.define("extole-require",[],function(){return{resolveUrl:h}});
setTimeout(function(){var d=!1,k=[];w(f,function(m){m._defined||(d=!0);k.push({defineStartTime:m.defineStartTime,dependencies:m.dependencies,end:m.end,start:m.start,isRequire:m.isRequire,timeToDefine:m.timeToDefine,url:m.url,_defined:m._defined,_defining:m._defining,_fetched:m._fetched})});d&&extole.DUMP_REQUIRE_MODULES_ON_ERROR&&extole.log("error","After 7000ms there are unresolved extole-require modules.  ###"+JSON.stringify(k)+"###")},7E3)}();(function(){})();
extole.define("extole-uri-parser",["https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/collection.js","https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/uri.js"],function(r,q){var w=/^extole_(?!zone)/,t=/^extole_zone_/;return new function(){function l(g){var e={};g=g||h;r.each(g,function(c,a){w.test(a)&&(a=a.replace(w,""),e[a]=c)});return e}function v(){var g,e,c={};this.withName=function(a){g=a;return this};this.withElementId=function(a){e=
a;return this};this.withData=function(a,b){c[a]=b;return this};this.build=function(){var a={};g&&(a.name=g);e&&(a.elementId=e);c&&(a.data=c);return a}}var h=q.deserialize(location.search);this.parseUriZoneDefinition=function(g){var e=new v,c;g=g||h;var a=l(g);r.each(a,function(b,f){e.withData(f,b)});r.each(g,function(b,f){t.test(f)&&(f=f.replace(t,""),"name"===f?(c=!0,e.withName(b)):"element_id"===f?e.withElementId(b):e.withData(f,b))});return c?e.build():null};this.parseGlobalZoneParameters=l}});
(function(r,q,w,t,l){r[q]=r[q]||{};for(r[q].q=r[q].q||[];l<t.length;)w(t[l++],r[q])})(window,"extole",function(r,q){q[r]=q[r]||function(){q.q.push([r,arguments])}},["createZone","log"],0);
(function(){var r=[{name:"Branded Program Domain",programDomain:"invite.soundcloud.com",sitePatterns:"invite.soundcloud.com my.extole.com *.my.extole.com soundcloud.com *.soundcloud.com soundcloud.io *.soundcloud.io soundcloud.com *.soundcloud.com".split(" "),siteRegexPatterns:"invite\\.soundcloud\\.com\\.?$ my\\.extole\\.com\\.?$ .*\\.my\\.extole\\.com\\.?$ soundcloud\\.com\\.?$ .*\\.soundcloud\\.com\\.?$ soundcloud\\.io\\.?$ .*\\.soundcloud\\.io\\.?$ soundcloud\\.com\\.?$ .*\\.soundcloud\\.com\\.?$".split(" ")}];extole.CORE_ROOT=
"https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24";extole.CORE_CONFIG={backendTargetingEnabled:!0,isCookieConsentEnabled:!1,isJsCreativeRespondsWithHtmlEnabled:!1,isGlobalZoneParametersEnabled:!0,isAccessTokenIncludedInResponseEnabled:!1,cookieConsentPolicy:"COOKIE_CONSENT_OR_SESSION_COOKIE",cookieConsentEnabled:!1};extole.CLIENT_ID="2132918291";extole.BUILD_DATE="1741419474386";extole.VERSION="6.0";extole.IS_DEBUG_ENABLED=extole.debug||/[?&]extole_debug=true(&|$)/.test(location.search);
extole.PROGRAM=function(){function q(e,c){e=Error.call(this,e);this.name="ExtoleError";this.message=e.message;this.stack=e.stack;this.code=c}function w(e,c){if(e.length)for(var a=0;a<e.length;a++)c(e[a],a);else for(a in e)Object.prototype.hasOwnProperty.call(e,a)&&c(e[a],a)}function t(e,c){var a=[];w(e,function(b){(b=c(b))&&(a[a.length]=b)});return a}function l(e,c){c=c||[];var a=!1;w(c,function(b){(new RegExp(b)).test(e)&&(a=!0)});return a}function v(){extole.require(["https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/uri.js",
"https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/ajax.js"],function(e,c){var a=extole.CORE_ROOT;e=a.replace(/(https?:\/\/[a-z-\.]+)(\/.*)/,"$1")+"/_extole_core.gif"+e.serialize({core_root:a,referer:window.location.hostname});c({url:e})})}q.prototype=Error();q.prototype.constructor=q;var h=function(e){var c=window.location.hostname;return t(e,function(a){if(l(c,a.siteRegexPatterns))return a})}(r),g=h[0];if(!g)throw v(),new q("No program domain is configured for hostname: "+
window.location.hostname+" unable to use Extole API","site_configuration_error");1<h.length&&extole.log("warn","Multiple programs matched hostname: "+window.location.hostname+" programs: "+JSON.stringify(h));return g}();extole.require(["https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/uri.js","https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/logger.js","create-zone-executor"],function(q,w,t){function l(){function e(a){var b=a[0];"function"===
typeof c[b]?(c[b].apply(null,a[1]),extole.q.history.push({name:a[0],args:a[1],timestamp:Date.now(),stack:Error().stack})):w.warn("Unable to execute method: "+b+", it is not implemented.")}var c={log:function(){var a=Array.prototype.slice.call(arguments),b=a[0];"function"===typeof w[b]&&w[b].apply(null,a.slice(1))},createZone:t.initiateExecution};for(extole.q.history=[];extole.q.length;)e(extole.q.shift());extole.q.push=e}function v(){extole.require(["extole-uri-parser"],function(e){var c=q.deserialize(location.search);
(e=e.parseUriZoneDefinition(c))&&extole.createZone(e)})}function h(){if("function"===typeof window.onerror)var e=window.onerror;window.onerror=function(c,a,b,f,n){if(e)try{e(c,a,b,f,n)}catch(k){}a=a||window.location.href||"no_source_or_location.href";n=n&&n.stack?n.stack:"no_error.stack";var p=[],d=JSON.stringify({MESSAGE:c,SOURCE:a,LINE_NUMBER:b,COLUMN_NUMBER:f,STACK_TRACE:n},function(k,m){if(null!==m&&"object"===typeof m){if(0<=p.indexOf(m))return;p.push(m)}return m});b=extole.PROGRAM.programDomain.split(".").join("\\.");
b=new RegExp("^(http|https):\\/\\/("+b+"|(([A-Za-z0-9-]{1,}\\.){1,}|)(xtlo\\.net|extole(\\.com|\\.io)))(?=(\\/|\\?|$))");((n+c).match(/extole/i)||b.test(a))&&extole.require(["https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/logger.js"],function(k){k.error("Unhandled exception",JSON.parse(d))})}}function g(){extole._bootstrapped=!0;h();l();v()}extole.bootstrap=g;extole._bootstrapped||g();if("undefined"!==typeof window.extoleAsyncInit)try{window.extoleAsyncInit()}catch(e){extole.require(["https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/logger.js"],
function(c){c.error("Error executing extended core javascript. Message : "+e.message+" Stack: "+e.stack)})}})})();
extole.define("https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/ExtoleError.js",[],function(){function r(w,t,l,v){w=Error.call(this,w);this.name="ExtoleError";this.message=w.message||"no_message";this.stack=Error().stack;this.code=t||"extole_error";this.data=l||{};this.logLevel=0<=q.indexOf(v)?v:"error"}var q=["debug","info","warn","error"];r.prototype=Error();r.prototype.constructor=r;r.prototype.toString=function(){return this.name+" ["+this.logLevel+"]: message: "+
this.message+"; code: "+this.code+"; data: "+JSON.stringify(this.data,null,4)+"; stack trace: "+this.stack+";"};return r});
extole.define("https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/collection.js",["https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/ExtoleError.js","https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/type.js"],function(r,q){function w(l,v){var h;if(l.length===Number(l.length))for(h=0;h<l.length;h++){var g=v(l[h],h);if(!1===g)return!1}else for(h in l)if(Object.prototype.hasOwnProperty.call(l,h)&&(g=v(l[h],
h),!1===g))return!1}function t(l){if(!l||"object"!==typeof l&&!q.isPlainFunction(l))l={};for(var v=1;v<arguments.length;v++)if(q.isPlainObject(arguments[v]))for(var h in arguments[v]){var g=arguments[v][h];g!==l&&void 0!==g&&(q.isPlainObject(g)&&q.isPlainObject(l[h])?g=t(l[h],g):q.isArray(g)&&q.isArray(l[h])&&l[h].concat&&(g=l[h].concat(g)),l[h]=g)}return l}w.BREAK=!1;return{each:w,map:function(l,v){function h(c,a){e=[];w(c,function(b,f){e.push(a(b,f))})}function g(c,a){e={};w(c,function(b,f){e[f]=
a(b,f)})}var e;if(q.isArray(l))h(l,v);else if(q.isPlainObject(l))g(l,v);else throw new r(l+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return e},filter:function(l,v){function h(c,a){e=[];w(c,function(b,f){a(b,f)&&e.push(b)})}function g(c,a){e={};w(c,function(b,f){a(b,f)&&(e[f]=b)})}var e;if(q.isArray(l))h(l,v);else if(q.isPlainObject(l))g(l,v);else throw new r(l+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return e},merge:t,clone:function(l){return JSON.parse(JSON.stringify(l))},
flatten:function(l){function v(g,e){if(q.isPlainObject(g))w(g,function(a,b){var f=e.slice();f.push(b);v(a,f)});else{var c=e.join(".");h[c]=g}}if(!q.isPlainObject(l))return l;var h={};v(l,[]);return h},find:function(l,v){var h;w(l,function(g,e){if(v(g,e))return h=g,w.BREAK});return h},reverse:function(l){var v=[];if(!l||l.length!==Number(l.length))return l;for(var h=l.length-1;0<=h;h--)v.push(l[h]);return v},nashornToJs:function(l){if(q.isPlainJs(l)||!l)return l;if(q.isJavaMap(l)){var v={};for(var h in l)v[h]=
l[h]}else if(q.isNumber(l.length))v=[],w(l,function(g,e){v[e]=g});else return l;return v},intersection:function(l,v){var h=[];w(l,function(g){0>v.indexOf(g)||0<=h.indexOf(g)||h.push(g)});return h},difference:function(l,v){var h=[];w(l,function(g){0<=v.indexOf(g)||0<=h.indexOf(g)||h.push(g)});return h}}});
extole.define("https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/cookie.js",["https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/logger.js"],function(r){function q(h){try{return decodeURIComponent(h.replace(t," "))}catch(g){return r.info("** cookie.decode ** Cookie error for: "+h,{error:g,message:g.message,stack:g.stack,cookiePart:h}),""}}function w(h){h=q(h);return 0===h.indexOf('"')?h.slice(1,-1).replace(l,'"').replace(v,"\\"):h}var t=
/\+/g,l=/\\"/g,v=/\\\\/g;return function(h,g,e){if(void 0!==g){e=e||{};var c=document;h=encodeURIComponent(h);g=encodeURIComponent(g);if(e.expires){var a=e.expires;if(!a||!a.toUTCString){var b=new Date;b.setDate(b.getDate()+("number"===typeof a?a:0));a=b}a="; expires="+a.toUTCString()}else a="";return c.cookie=[h,"=",g,a,e.path?"; path="+e.path:"",e.domain?"; domain="+e.domain:"",e.samesite?"; samesite="+e.samesite:"","; secure"].join("")}a:{e=document.cookie?document.cookie.split("; "):[];c=h?null:
{};g=0;for(a=e.length;g<a;g++){b=e[g].split("=");var f=q(b[0]);if(!h)c[f]=w(b[1]);else if(h===f){h=w(b[1]);break a}}h=c}return h}});
extole.define("https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/device-type.js",[],function(){function r(t){return q.test(t)}var q=RegExp("Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|Dolphin|Fennec|(hpw|web)OS|Zune|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Silk-Accelerated|Skyfire|NetFront","i"),w=/WebView|\swv|(iPhone|iPod|iPad)(?!.*Safari)|Android.*(Version\/\d+\.\d+\s)|Linux; U; Android/i;return{isMobile:r,isDesktop:function(t){return!r(t)},isWebview:function(t){return w.test(t)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/dom.js",["https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/logger.js"],function(r){function q(c,a){return(a||document).querySelectorAll(c)}function w(c,a){return q(c,a)[0]}function t(c,a){function b(){clearTimeout(n);a(f);v.removeListener(f,"load",b)}a=a||function(){};if(e[c]||!c)return a(e[c]),e[c]||null;e[c]=document.createElement("link");var f=e[c];h.setAttribute(f,
"rel","stylesheet");h.setAttribute(f,"href",c);g.append(w("head"),f);v.addListener(f,"load",b);var n=setTimeout(function(){r.warn("Load timeout reached for stylesheet: ",{url:c});b()},5E3);return f}var l={each:function(c,a){var b;if(c.length===Number(c.length))for(b=0;b<c.length;b++){var f=a(c[b],b);if(!1===f)return!1}else for(b in c)if(Object.prototype.hasOwnProperty.call(c,b)&&(f=a(c[b],b),!1===f))return!1},extend:function(){var c,a,b=arguments[0]||{},f=1,n=arguments.length,p=!1,d=this.extend;"boolean"===
typeof b&&(p=b,b=arguments[1]||{},f=2);for("object"===typeof b||this.isFunction(b)||(b={});f<n;f++){var k=arguments[f];if(null!==k)for(c in k){var m=b[c];var u=k[c];b!==u&&(p&&u&&(this.isPlainObject(u)||(a=this.isArray(u)))?(a?(a=!1,m=m&&this.isArray(m)?m:[]):m=m&&this.isPlainObject(m)?m:{},b[c]=d(p,m,u)):void 0!==u&&(b[c]=u))}}return b},isFunction:function(c){return c&&"function"===typeof c&&c.call&&c.apply},isPlainObject:function(c){if("[object Object]"!==String(c)||c.nodeType||c.window&&c.window==
c)return!1;try{if(c.constructor&&!Object.prototype.hasOwnProperty.call(c.constructor.prototype,"isPrototypeOf"))return!1}catch(a){return!1}return!0},isArray:function(c){return c instanceof Array}};l.each.BREAK=!1;var v=function(){function c(p,d,k){for(var m=[],u=0;u<n.length;u++){var x=n[u];x.element==p&&x.eventType==d&&x.listener==k&&m.push({index:u,eventListener:x})}return m}function a(p){for(var d=[],k=0;k<n.length;k++){var m=n[k];m.element===p&&d.push(m)}return d}function b(p){this.originalEvent=
p;this.type=p.type;this.keyCode=p.keyCode;this.target=p.srcElement?p.srcElement:p.target}function f(p,d,k){k=c(p,d,k);0>=k.length?r.info("events.remove - Couldn't find exiting event listener for type \""+d+'" listener on element '+p):l.each(k,function(m){var u=m.index;m=m.eventListener;p.removeEventListener?p.removeEventListener(d,m.listenerWrapper,!1):p.detachEvent("on"+d,m.listenerWrapper);n.splice(u,1)})}var n=[];b.prototype={preventDefault:function(){var p=this.originalEvent;p.preventDefault?
p.preventDefault():p.returnValue=!1},stopPropagation:function(){var p=this.originalEvent;p.stopPropagation&&p.stopPropagation();p.cancelBubble=!0}};return{addListener:function(p,d,k){function m(x){u&&(x=window.event);return k.call(p,new b(x))}if(0<c(p,d,k).length)r.warn("events.add - Listener already exists for event "+d+" on element "+p);else{var u=!p.addEventListener;n.push({element:p,eventType:d,listener:k,listenerWrapper:m});p.addEventListener?p.addEventListener(d,m,!1):p.attachEvent("on"+d,m)}},
triggerEvent:function(p,d,k){var m=document.createEvent("Event");k=l.extend({},k);var u=!1===!k.bubbles,x=!0===k.cancelable;delete k.bubbles;delete k.cancelable;m.initEvent(d,u,x);l.extend(m,k);p.dispatchEvent(m)},removeListener:f,clearListeners:function(p){p=a(p);l.each(p,function(d){f(d.element,d.eventType,d.listener)})}}}(),h=function(){function c(b){b=b.className;var f={};if(!b)return f;l.each(b.split(" "),function(n){f[n]=1});return f}function a(b){var f="";l.each(b,function(n,p){f+=" "+p});
return f.slice(1)}return{setAttribute:function(b,f,n){b.setAttribute(f,n);b[f]=n},getAttribute:function(b,f){return b.getAttribute(f)},removeAttribute:function(b,f){return b.removeAttribute(f)},addClass:function(b,f){var n=c(b);n[f]||(n[f]=1,b.className=a(n))},removeClass:function(b,f){var n=c(b);delete n[f];b.className=a(n)},getClassNames:function(b){return b.className.split(" ")}}}(),g=function(){function c(b){var f=document.createDocumentFragment(),n=document.createElement("div");n.innerHTML=b;
l.each(n.childNodes,function(p){1==p.nodeType&&f.appendChild(p)});return f}function a(b){var f;l.each(b.childNodes,function(n){if(!f&&1==n.nodeType)return f=n,l.each.BREAK});return f}return{prepend:function(b,f){var n=a(b),p=f;"string"===typeof f&&(p=c(f));n?b.insertBefore(p,n):b.appendChild(p)},append:function(b,f){var n=f;"string"===typeof f&&(n=c(f));b.appendChild(n)}}}(),e={};return{addEventListener:v.addListener,removeEventListener:v.removeListener,triggerEvent:v.triggerEvent,clearEventListeners:v.clearListeners,
getAttribute:h.getAttribute,setAttribute:h.setAttribute,removeAttribute:h.removeAttribute,addClass:h.addClass,removeClass:h.removeClass,getClassNames:h.getClassNames,prepend:g.prepend,append:g.append,query:q,queryFirst:w,isVisible:function(c,a){return!!(w(c,a)||{}).offsetParent},injectStylesheet:t,injectStylesheets:function(c,a){function b(p){--f||a(n)}a=a||function(){};if(0===c.length)a();else{var f=0,n=[];l.each(c,function(p){f++;setTimeout(function(){n.push(t(p,b))},1)})}},scrollIntoViewIfNeeded:function(c,
a){function b(u,x){return{start:u,length:x,end:u+x}}function f(u,x){return!1===a||x.start<u.end&&u.start<x.end?Math.min(u.start,Math.max(x.start,u.end-x.length)):(u.start+u.end-x.length)/2}function n(u,x){return{x:u,y:x,translate:function(C,z){return n(u+C,x+z)}}}function p(u,x){for(;u;)x=x.translate(u.offsetLeft,u.offsetTop),u=u.offsetParent;return x}var d=p(c,n(0,0)),k=n(c.offsetWidth,c.offsetHeight);c=c.parentNode;for(var m;c instanceof HTMLElement;)m=p(c,n(c.clientLeft,c.clientTop)),c.scrollLeft=
f(b(d.x-m.x,k.x),b(c.scrollLeft,c.clientWidth)),c.scrollTop=f(b(d.y-m.y,k.y),b(c.scrollTop,c.clientHeight)),d=d.translate(-c.scrollLeft,-c.scrollTop),c=c.parentNode}}});
extole.define("https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/event-bus.js",[],function(){function r(){function t(h,g,e,c){if(!e)return!0;if("object"===typeof e){for(var a in e)h[g].apply(h,[a,e[a]].concat(c));return!1}if(v.test(e)){e=e.split(v);a=0;for(var b=e.length;a<b;a++)h[g].apply(h,[e[a]].concat(c));return!1}return!0}function l(h,g){var e,c=-1,a=h.length,b=g[0],f=g[1],n=g[2];switch(g.length){case 0:for(;++c<a;)(e=h[c]).callback.call(e.ctx);break;case 1:for(;++c<
a;)(e=h[c]).callback.call(e.ctx,b);break;case 2:for(;++c<a;)(e=h[c]).callback.call(e.ctx,b,f);break;case 3:for(;++c<a;)(e=h[c]).callback.call(e.ctx,b,f,n);break;default:for(;++c<a;)(e=h[c]).callback.apply(e.ctx,g)}}this._events={};var v=/\s+/;this.on=function(h,g,e){if(!t(this,"on",h,[g,e])||!g)return this;this._events||(this._events={});(this._events[h]||(this._events[h]=[])).push({callback:g,context:e,ctx:e||this});return this};this.off=function(h,g,e){var c,a,b;if(!this._events||!t(this,"off",
h,[g,e]))return this;if(!h&&!g&&!e)return this._events=void 0,this;var f=h?[h]:w.keys(this._events);var n=0;for(a=f.length;n<a;n++)if(h=f[n],c=this._events[h]){var p=[];this._events[h]=p;if(g||e){var d=0;for(b=c.length;d<b;d++){var k=c[d];(g&&g!==k.callback&&g!==k.callback._callback||e&&e!==k.context)&&p.push(k)}}p.length||delete this._events[h]}return this};this.once=function(h,g,e){function c(){var b=q.call(arguments);a.off(h,c,e);g.apply(this,b)}var a=this;this.on(h,c,e);return this};this.trigger=
function(h){if(!this._events)return this;var g=q.call(arguments,1);if(!t(this,"trigger",h,g))return this;var e=this._events[h],c=this._events.all;e&&l(e,g);c&&l(c,arguments);return this}}var q=Array.prototype.slice,w={isPlainObject:function(t){if("[object Object]"!==String(t)||t.nodeType||t.window&&t.window==t)return!1;try{if(t.constructor&&!Object.prototype.hasOwnProperty.call(t.constructor.prototype,"isPrototypeOf"))return!1}catch(l){return!1}return!0},keys:function(t){if(!this.isPlainObject(t))return[];
var l=[],v;for(v in t)Object.prototype.hasOwnProperty.call(t,v)&&l.push(v);return l},_idCounter:0,uniqueId:function(t){var l=String(++this._idCounter);return t?t+l:l}};return{create:function(){return new r}}});
extole.define("https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/logger.js",[],function(){function r(b,f,n){l||(l=f.getGlobalServices().getJsLoggingService());l[b](n)}function q(b,f,n){var p=String(extole.CORE_ROOT).match(/coreAssetsVersion=(\d+)/);n=n||{};n.pageId=h;n.referer=g;n.coreAssetsVersion=p&&p[1];try{var d=[f||"no message","START_JSON",JSON.stringify(n),"END_JSON"].join(" ")}catch(k){t("Failed to stringify log's json data",{exception:k});return}if(!extole.LOG_EXCLUDE_REGEX||
!d.match(extole.LOG_EXCLUDE_REGEX)){a[d]=++a[d]||1;if(e[b]>=e[extole.LOG_LEVEL_CONSOLE]&&(f=b+" "+d,window.console))if(window.console[b.toLowerCase()])window.console[b.toLowerCase()](f);else window.console.log(f);e[b]>=e[extole.LOG_LEVEL_REMOTE]&&(f=a[d],c[f]&&w(b,d+(1<f?" log count: "+f:"")))}}function w(b,f){extole.require(["https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/api.js"],function(n){n.post("/api/v4/debug/logs",{level:b,message:f},null,{headers:{"Content-Type":"application/x-www-form-urlencoded"}})})}
function t(b,f){q("ERROR",b,f)}var l;if("undefined"===typeof window)return{debug:function(b,f){r("debug",b,f)},info:function(b,f){r("info",b,f)},warn:function(b,f){r("warn",b,f)},error:function(b,f){r("error",b,f)},LOGGING_ENDPOINT:"/api/v4/debug/logs"};var v=extole.IS_DEBUG_ENABLED?"DEBUG":"OFF",h=String((new Date).getTime()),g=window.location.href,e={DEBUG:0,INFO:1,WARN:2,ERROR:3,OFF:4},c={1:!0,3:!0,10:!0,30:!0,100:!0,250:!0,500:!0,1E3:!0};extole.LOG_EXCLUDE_REGEX=extole.LOG_EXCLUDE_REGEX||void 0;
extole.LOG_LEVEL_CONSOLE=extole.LOG_LEVEL_CONSOLE||v;extole.LOG_LEVEL_REMOTE=extole.LOG_LEVEL_REMOTE||"WARN";var a={};return{debug:function(b,f){q("DEBUG",b,f)},info:function(b,f){q("INFO",b,f)},warn:function(b,f){q("WARN",b,f)},error:t,LOGGING_ENDPOINT:"/api/v4/debug/logs"}});
extole.define("https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/Timer.js",[],function(){return function(){var r=this,q;this.start=function(){if(q)throw Error("Timer.start has already been called");q=new Date;return r};this.getElapsedTime=function(){if(!q)throw Error("Timer has not been started");return new Date-q}}});
extole.define("https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/type.js",[],function(){function r(t,l){return function(v){return q(t,v,l)}}function q(t,l,v){v=v||{};t=Object.prototype.toString.call(l)==="[object "+t+"]";l=l&&v.construct?l.constructor===v.construct:!0;return(v.negate?!t:t)&&l}var w=/\[object (Function|Array|String|Boolean|Number|Undefined|Null)\]/;return{isPlainJs:function(t){return this.isPlainObject(t)||w.test(Object.prototype.toString.call(t))},
isJavaMap:function(t){return"undefined"!==typeof Java&&Java.type?t instanceof Java.type("java.util.Map"):!1},isPlainObject:r("Object",{construct:Object}),isPlainFunction:r("Function"),isArray:r("Array"),isString:r("String"),isBoolean:r("Boolean"),isNumber:r("Number"),isUndefined:r("Undefined"),isDefined:r("Undefined",{negate:!0}),isNull:r("Null"),test:q}});
extole.define("https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/uri.js",["https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/collection.js"],function(r){function q(g){var e={};(function f(a,b){for(var n in a){var p=a[n],d=(b?b+".":"")+n;"[object Object]"===Object.prototype.toString.call(p)?f(p,d):t(d)&&(e[d]=p)}})(g);return e}function w(g){try{return decodeURIComponent(g)}catch(e){return g}}function t(g){return"__proto__"!==g&&"prototype"!==
g&&"constructor"!==g}function l(g,e,c){e=(e||[]).concat("object"===typeof extole&&extole.PROGRAM?extole.PROGRAM.siteRegexPatterns:[]);c=v(c||location.href);g=v(g);return(/^https?:\/\//.test(g)?r.find(e,function(a){var b=h.exec(g);return(new RegExp(a)).test(b&&b[1])}):1)?g:c}function v(g){return g.replace(RegExp("(j|%4A|%6A)(a|%41|%61)(v|%56|%76)(a|%41|%61)(s|%53|%73)(c|%43|%63)(r|%52|%72)(i|%49|%69)(p|%50|%70)(t|%54|%74)(:|%3A)","gi"),"")}var h=/^https?:\/\/([^/:?#]+)/i;return{serialize:function(g){var e=
"",c;for(c in g)e+="&"+encodeURIComponent(c)+"="+encodeURIComponent(String(g[c]));return e.replace(/^&/,"?")},deserialize:function(g){var e={};if(!g)return e;g=(g.match(/^\?/)?g.slice(1):g).split("&");for(var c=0;c<g.length;c++){var a=g[c].split("="),b=w(a[0]);a=w(a[1]);t(b)&&(e[b]=a)}return e},objectToDotNotation:q,dotNotationToObject:function(g){var e={};g=q(g);for(var c in g){for(var a=e,b=c.split("."),f=b.pop();b.length;){var n=b.shift();t(n)&&(a[n]=a[n]||{},a=a[n])}t(f)&&(a[f]=g[c])}return e},
decodeComponent:w,encodeComponent:function(g){return encodeURIComponent(g)},getSafeRedirectUrl:l,executeSafeRedirect:function(g,e,c){window.location.href=l(g,e,c)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/ajax.js",["https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/collection.js","https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/uri.js","https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/type.js","https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/logger.js","https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/client/token-store.js"],
function(r,q,w,t,l){function v(a,b){function f(){if(4===a.readyState&&!F){F=!0;var E=a.status||200;if(String(E).match(/^[23]/))"function"===typeof B?(E=n(a.getAllResponseHeaders()),E["x-extole-token"]&&l.set(E["x-extole-token"]),B.call(a,a.responseText,a)):t.warn("'complete' callback must be a function.");else{try{var G=JSON.parse(a.responseText)}catch(H){G=""}403!==E||"invalid_access_token"!==G.code&&"expired_access_token"!==G.code||l.remove();y.call(a,a.statusText,a.status)}k()}}function n(E){try{var G=
{};E.trim().split(/[\r\n]+/).forEach(H=>{var I=H.split(": ");H=I.shift();I=I.join(": ");G[H]=I});return G}catch(H){return t.error("Error parsing response headers: ",H),{}}}function p(E){F||(F=!0,t.error("Error with url "+C+"= "+m.join(","),d(E)),y.call(a,a.statusText,a.status))}function d(E){return{eventType:E&&E.type||null,options:b,readyState:a.readyState,response:a.response,responseText:a.responseText,responseType:a.responseType,responseURL:a.responseURL,responseXML:a.responseXML,status:a.status,
statusText:a.statusText,timeout:a.timeout,responseHeaders:a.getAllResponseHeaders()}}function k(E){0>C.indexOf(t.LOGGING_ENDPOINT)&&t.debug("ajax request complete",d(E))}var m=Array.prototype.slice.call(arguments),u=b.headers||{},x=b.xhrFields||{},C=b.url||"",z=b.data||"",D=(b.type||"get").toUpperCase(),B=b.complete||function(){},y=b.error||function(){},A=l.get();C.includes("/api/")&&A&&!b.noAuthorizationHeader?u.Authorization=A:C.includes("/zones/")&&(A&&!b.noAuthorizationHeader&&(u.Authorization=
"Bearer+"+A),"GET"!==D&&"HEAD"!==D&&(z=h(u,z)));w.isPlainObject(z)&&("GET"===D?(C+=q.serialize(z),z=null):z=JSON.stringify(z));a.open(D,C,!0);r.merge(a,x);r.each(u,function(E,G){try{a.setRequestHeader(G,E)}catch(H){t.error("AJAX ERROR: Couldn't set request header "+G+" to "+E)}});var F=!1;a.onload=f;a.onreadystatechange=f;a.onerror=p;a.ontimeout=p;a.onabort=k;a.send(z)}function h(a,b){function f(p){var d={};r.each(p,function(k,m){m=0<=m.indexOf(".")?'"'+m+'"':m;w.isPlainObject(k)&&(k=f(k));d[m]=k});
return d}var n=[];g(a);a["content-type"]="application/x-www-form-urlencoded";b=f(b);b=r.flatten(b);r.each(a,function(p,d){"content-type"!==d.toLowerCase()&&(n.push("::headers."+d+"="+p),delete a[d])});r.each(b,function(p,d){w.isUndefined(p)||n.push(encodeURIComponent(d)+"="+(w.isNull(p)?"":encodeURIComponent(p)))});return n.join("&")}function g(a){r.each(a,function(b,f){"content-type"===f.toLowerCase()&&delete a[f]})}function e(a){a=a||{};var b=!1;for(var f=0;f<c.length;f++){try{b=c[f]()}catch(n){continue}break}v(b,
a);return b}var c=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}];e.convertToFormUrlEncoded=h;e.convertToMultipartFormData=function(a,b){var f=new FormData;r.each(b,function(n,p){f.append(p,n)});g(a);return f};return e});
extole.define("https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/client/program.js",[],function(){return{getName:function(){return extole.PROGRAM.name},getProgramDomain:function(){return extole.PROGRAM.programDomain},getSitePatterns:function(){return extole.PROGRAM.sitePatterns},getSiteRegexPatterns:function(){return extole.PROGRAM.siteRegexPatterns},getProtocol:function(){return"https://"}}});
extole.define("https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/client/token-store.js","https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/ExtoleError.js https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/collection.js https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/uri.js https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/logger.js https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/event-bus.js https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/cookie.js".split(" "),
function(r,q,w,t,l,v){function h(){function b(){B[c.MEMORY]=B[c.MEMORY]||new p;B[c.COOKIE]=B[c.COOKIE]||new d;B[c.LOCAL_STORAGE]=B[c.LOCAL_STORAGE]||new k;extole.COOKIES_DISABLED&&(B[c.COOKIE].remove(),delete B[c.COOKIE]);extole.LOCAL_STORAGE_ALWAYS_ENABLED||extole.LOCAL_STORAGE_ENABLED_WHEN_CONSENTED||extole.LOCAL_STORAGE_ENABLED_WHEN_UNCONSENTED||(B[c.LOCAL_STORAGE].remove(),delete B[c.LOCAL_STORAGE])}function f(){var y=z===e.YEAR?x():C();return(y=q.find(y,function(A){A=A.get();return!("string"!==
typeof A||"undefined"===A||"null"===A||!A.length)}))?y.get():null}function n(y,A){var F=f();if(!y&&F)y=F;else if(!y&&!F)return;var E=F!==y;z=Object.prototype.hasOwnProperty.call(e,A)&&A||(E||!z?m():z);u(z);q.each(z===e.YEAR?x():C(),function(G){G.set(y,z)});E&&D.trigger("change:access_token");F&&E&&t.debug("ACCESS_TOKEN_CHANGE - the access token changed from: "+F+", to: "+y)}function p(){var y={};this.get=function(){return y.extole_access_token};this.set=function(A){y.extole_access_token=A};this.remove=
function(){delete y.extole_access_token}}function d(){this.get=function(){return v("extole_access_token")};this.set=function(y,A){v("extole_access_token",y,{expires:a[A.toUpperCase()],path:"/",samesite:"strict"})};this.remove=function(){v("extole_access_token","",{expires:-1,path:"/"})}}function k(){var y;(function(){var A="test"+(new Date).getTime();try{localStorage.setItem(A,A),localStorage.removeItem(A)}catch(F){y=!1;return}y=!0})();this.get=function(){return y?localStorage.getItem("extole_access_token"):
null};this.set=function(A){y&&localStorage.setItem("extole_access_token",A)};this.remove=function(){y&&localStorage.removeItem("extole_access_token")}}function m(){if(extole.CORE_CONFIG.isCookieConsentEnabled)switch(extole.CORE_CONFIG.cookieConsentPolicy){case g.COOKIE_CONSENT_OR_SESSION_COOKIE:return e.SESSION;case g.COOKIE_CONSENT_OR_NO_COOKIE:return e.NO_COOKIE;default:return e.NO_COOKIE}return e.YEAR}function u(){var y=z===e.YEAR?x():C();q.each(B,function(A){0>y.indexOf(A)&&A.remove()})}function x(){var y=
[c.MEMORY];Object.prototype.hasOwnProperty.call(B,c.COOKIE)&&y.push(c.COOKIE);(extole.LOCAL_STORAGE_ENABLED_WHEN_CONSENTED||extole.LOCAL_STORAGE_ALWAYS_ENABLED)&&y.push(c.LOCAL_STORAGE);return y.map(function(A){return B[A]})}function C(){var y=[c.MEMORY];extole.CORE_CONFIG.cookieConsentPolicy===g.COOKIE_CONSENT_OR_SESSION_COOKIE&&Object.prototype.hasOwnProperty.call(B,c.COOKIE)&&y.push(c.COOKIE);(extole.LOCAL_STORAGE_ENABLED_WHEN_UNCONSENTED||extole.LOCAL_STORAGE_ALWAYS_ENABLED)&&y.push(c.LOCAL_STORAGE);
return y.map(function(A){return B[A]})}var z,D=l.create(),B={};b();(function(){var y=w.deserialize(window.location.search);y.extole_access_token&&n(y.extole_access_token,y.extole_access_token_type)})();this.getCurrentTokenDuration=function(){return z};this.get=f;this.set=n;this.remove=function(){z=m();q.each(B,function(y){y.remove()})};this.setConsented=function(){z="YEAR";n()};this.setUnconsented=function(){z=m();n()};this.initializeStores=b;this.events=D}var g={COOKIE_CONSENT_DISABLED:"COOKIE_CONSENT_DISABLED",
COOKIE_CONSENT_OR_SESSION_COOKIE:"COOKIE_CONSENT_OR_SESSION_COOKIE",COOKIE_CONSENT_OR_NO_COOKIE:"COOKIE_CONSENT_OR_NO_COOKIE"},e={NO_COOKIE:"NO_COOKIE",SESSION:"SESSION",YEAR:"YEAR"},c={MEMORY:"MEMORY",COOKIE:"COOKIE",LOCAL_STORAGE:"LOCAL_STORAGE"},a={YEAR:365,SESSION:null};extole.tokenStore=extole.tokenStore?extole.tokenStore:new h;return extole.tokenStore});
extole.define("https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/client/metric-registry.js",["https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/client/program.js","https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/ajax.js","https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/logger.js"],function(r,q,w){function t(h,g,e){w.info("Sending metric from metric registry: "+h+" "+
g+" "+e);e={metric_type:h,key:g,value:e};h={"Content-Type":"application/x-www-form-urlencoded","X-Extole-App":"javascript_sdk"};g=[r.getProtocol(),r.getProgramDomain(),"/api/v4/debug/metrics"].join("");e=q.convertToFormUrlEncoded(h,e);q({url:g,type:"POST",headers:h,data:e,xhrFields:{withCredentials:!0}})}function l(h){this.increment=function(g){t("COUNTER",h,g?g:1)}}function v(h){this.update=function(g){t("HISTOGRAM",h,g)}}return{histogram:function(h){return new v(h)},counter:function(h){return new l(h)}}});
extole.define("ZoneBrowserContext",["https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/uri.js","https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/collection.js"],function(r,q){function w(v,h,g){this.getElement=function(){return g};this.getName=function(){return v};this.getData=function(){return h};this.getParameters=function(){return h}}function t(){this.getName=function(){return extole.PROGRAM.name};this.getProgramDomain=function(){return extole.PROGRAM.programDomain};
this.getSitePatterns=function(){return extole.PROGRAM.sitePatterns};this.getSiteRegexPatterns=function(){return extole.PROGRAM.siteRegexPatterns}}function l(){this.backendTargetingEnabled=function(){return!0};this.cookieConsentEnabled=function(){return extole.CORE_CONFIG.isCookieConsentEnabled}}return function(v,h,g,e,c){var a=new w(v,h,g),b=new t,f=new l;this.getZone=function(){return a};this.getProgram=function(){return b};this.getCreativeData=function(){var n=r.dotNotationToObject(r.deserialize(location.search)),
p=r.dotNotationToObject(a.getParameters());return q.merge(n.extole_creative,p.creative)};this.getCoreConfig=function(){return f};this.getLocale=function(){return e||null};this.getContainer=function(){return c}}});
extole.define("find-element-by-id",["https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/logger.js"],function(r){function q(w,t,l){function v(){if(t())l();else{w();var g=setTimeout;h||(h=10);var e=500<h?500:h*=1.1;g(v,e)}}var h;v()}return function(w,t){var l=(new Date).getTime(),v=extole.MILLISECONDS_TO_WARN_WHEN_ELEMENT_NOT_FOUND||3E3,h=extole.MILLISECONDS_TO_WARN_WHEN_ELEMENT_FOUND||2E3,g=!1,e;q(function(){e=document.getElementById(w)},function(){var c=(new Date).getTime()-
l,a=!!e;a&&c>=h?r.debug("EXTOLE_ELEMENT_FOUND_SLOW: Scan duration: "+c+"ms, element id: "+w):!extole.isFindElementBeforeZoneRequest&&!g&&c>=v&&(g=!0,r.debug("EXTOLE_ELEMENT_NOT_YET_FOUND: Scan duration: "+c+"ms, element id: "+w));return a},function(){t(e)})}});extole.define("ensure-element",["find-element-by-id"],function(r){return function(q,w){q.element?w(q.element):q.element_id?r(q.element_id,w):w(document.body.appendChild(document.createElement("div")))}});
extole.define("pending-zone-service","https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/dom.js https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/type.js https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/logger.js https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/collection.js ZoneBrowserContext ensure-element".split(" "),function(r,q,w,t,l,v){function h(a,b){b=b||function(){};
var f=a.name,n=g(a.data);c(f);this.resolve=function(p,d,k,m,u){v(a,function(x){a.element=x;r.clearEventListeners(a.element);x=new l(f,n,a.element,m,u);p(x);b(null,x.getZone())})}}function g(a){a=t.merge({},a);delete a.campaign_id;delete a.extole_campaign_id;return a}var e={},c=function(){var a={};return function(b){q.isUndefined(a[b])&&(a[b]=0);a[b]++;if(5===a[b]){b="duplicate_zone_requests : "+b;var f=t.filter(extole.q.history,function(n){return n.name&&"createZone"===n.name});f=t.map(f,function(n){delete (n.args[0]||
{}).element;return n});w.warn(b,f)}}}();return{get:function(a){if(!e[a])throw Error("Pending zone does not exist for id: "+a);return e[a]},create:function(){var a=Math.floor(1E9*Math.random()),b=0;return function(f,n){b++;var p=a+"."+b;e[p]=new h(f,n);return p}}()}});
extole.define("create-zone","extole-uri-parser https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/uri.js https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/collection.js https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/dom.js https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/client/program.js https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/ajax.js https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/ExtoleError.js https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/logger.js pending-zone-service".split(" "),function(r,
q,w,t,l,v,h,g,e){var c=[];return function(a,b,f){function n(){var D={"Content-Type":"application/x-www-form-urlencoded",Accept:"text/javascript","X-Extole-App":"javascript_sdk"};k=C+"/zones/"+a.name;x&&(D["X-Extole-Jwt"]=x,delete u.jwt);z&&(D["X-Extole-Debug"]="true");v({url:k,type:"POST",headers:D,data:u,complete:function(B,y){var A=/^text\/html(;|$)/,F=/^text\/plain(;|$)/;y=y.getResponseHeader("Content-Type");if(/^text\/javascript(;|$)/.test(y))var E=B;else A.test(y)?(A=document.createElement("div"),
A.innerHTML=B,E=t.queryFirst("script",A).innerHTML):F.test(y)&&!B?g.info("No content to render"):p(new h("Received invalid content type: '"+y+"'","invalid_content_type",null,"warn"));if(E)try{(new Function(E))()}catch(G){p(new h("Error in zone script - MESSAGE: "+G.message+" STACK: "+G.stack,"zone_script_error"))}d()},error:function(B,y){try{var A=JSON.parse(this.responseText)}catch(F){A={status:y||null,statusText:B||null}}p(new h(A.message||"Ajax zone request failed",A.code||null,A))},xhrFields:{withCredentials:!0}})}
function p(D){var B=w.merge({originalMessage:D.message,zoneRequestUrl:k||null,zoneDefinition:a},D.data);b(new h("Problem creating zone",D.code||"zone_request_failed",B,D.logLevel||"error"));d()}function d(){"function"===typeof f&&setTimeout(f,500)}b=b||function(){};var k,m=q.deserialize(location.search),u=w.merge({},a.data||a.parameters),x=a.jwt||u.jwt||m.extole_jwt,C=[l.getProtocol(),l.getProgramDomain()].join(""),z=u.debug&&"false"!==u.debug||extole.IS_DEBUG_ENABLED;extole.isPassRefererInZoneData&&
(u.referer=location.href);extole.CORE_CONFIG.isGlobalZoneParametersEnabled&&(m=r.parseGlobalZoneParameters(m),u=w.merge(u,m));if(extole.createZonePrehandler&&(m=extole.createZonePrehandler(a,u),!1===m)){g.info("Zone request cancelled");return}a.element_id&&(u.element_id=a.element_id);(function(){var D=Date.now(),B=D-6E4;c=c.filter(function(y){return y>B});60<c.length?g.warn("Zone request "+a.name+" exceeded maximum number of zone requests per minute: 60"):c.push(D);a.data=u;u.zone_id=e.create(a,b);
u=w.flatten(u);n()})()}});
extole.define("create-zone-executor",["create-zone","ensure-element","https://origin.xtlo.net/type=core:clientId=2132918291:coreAssetsVersion=24/common/logger.js"],function(r,q,w){function t(c,a,b){function f(d,k){d?n(d):(g=!0,(a||function(){}).apply(null,k),p())}function n(d){function k(){setTimeout(function(){l(c,a,b)},1)}b+=1;5>b?k():(w[d.logLevel||"error"](d.toString()),a(d))}var p;h.push(function(d){p=v(d);r(c,f,p);g&&p()})}function l(c,a,b){function f(){var n=!!c.element;extole.isFindElementBeforeZoneRequest&&
!n||t(c,a,b)}b=Number(b)||0;extole.isFindElementBeforeZoneRequest?q(c,function(n){c.element=n;f()}):f()}function v(c){var a=!1;return function(){var b=Array.prototype.slice.call(arguments);a||(a=!0,c.apply(null,b))}}var h=new function(){var c=0,a=[],b=this,f=!1;this.push=function(n){a.push(n);this.next()};this.next=function(){function n(){c--;g=!0;b.next()}if(!f)for(;1>c&&a.length;)e||g||this.next(),e=!1,a.shift()(n),c++};this.start=function(){f=!1;this.next()};this.stop=function(){f=!0}},g=!1,e=
!0;return{initiateExecution:l}});